version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      ruby-deps:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/scripts/og-image-gen"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      js-deps:
        patterns: ["*"]

  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "monthly"
